// Hive types appear throughout this package's public API — openBox returns a
// Box, openLazyBox a LazyBox, watch a Stream<BoxEvent>, registerAdapter takes a
// TypeAdapter. Re-exporting them means a consumer can write those types in its
// own signatures without adding `hive` to its pubspec (adapters generated by
// hive_generator are the exception: they emit their own hive import).
//
// HiveCipher and HiveAesCipher are here for the same reason: encrypting a box
// means naming the cipher type at the call site.
export 'package:hive/hive.dart'
    show
        BinaryReader,
        BinaryWriter,
        Box,
        BoxBase,
        BoxEvent,
        HiveAesCipher,
        HiveCipher,
        HiveError,
        HiveObject,
        HiveObjectMixin,
        LazyBox,
        TypeAdapter;

export 'src/baaba_storage.dart';
