// Hive types appear throughout this package's public API — openBox returns a
// Box, openLazyBox a LazyBox, watch a Stream<BoxEvent>, registerAdapter takes a
// TypeAdapter. Re-exporting them means a consumer can write those types in its
// own signatures without adding `hive_ce` to its pubspec (adapters generated by
// hive_ce_generator are the exception: they emit their own hive_ce import).
//
// HiveCipher and HiveAesCipher are here for the same reason: encrypting a box
// means naming the cipher type at the call site.
export 'package:hive_ce/hive_ce.dart'
    show
        BinaryReader,
        BinaryWriter,
        Box,
        BoxBase,
        BoxEvent,
        HiveAesCipher,
        HiveCipher,
        HiveError,
        HiveObject,
        HiveObjectMixin,
        LazyBox,
        TypeAdapter;

// The platform option types for the same reason: BaabaStorage.init and
// SecureStorage.configure take them, so a consumer customising secure storage
// should not need flutter_secure_storage in its own pubspec.
export 'package:flutter_secure_storage/flutter_secure_storage.dart'
    show
        AndroidOptions,
        IOSOptions,
        KeychainAccessibility,
        LinuxOptions,
        MacOsOptions,
        WebOptions,
        WindowsOptions;

export 'src/baaba_storage.dart';
